# Generated by Django 4.0.4 on 2022-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fusers', models.IntegerField(max_length=4294967295)),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Susers', models.IntegerField(max_length=4294967295)),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Third', models.IntegerField(max_length=4294967295)),
            ],
        ),
        migrations.DeleteModel(
            name='Ger',
        ),
        migrations.DeleteModel(
            name='Uz',
        ),
    ]
