# Generated by Django 4.0.4 on 2022-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0002_first_second_third_delete_ger_delete_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='second',
            old_name='Susers',
            new_name='Fusers',
        ),
        migrations.RenameField(
            model_name='third',
            old_name='Third',
            new_name='Fusers',
        ),
        migrations.AddField(
            model_name='first',
            name='Iusers',
            field=models.IntegerField(default=1, max_length=4294967295),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='first',
            name='Tusers',
            field=models.IntegerField(default=1, max_length=4294967295),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='second',
            name='Iusers',
            field=models.IntegerField(default=1, max_length=4294967295),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='second',
            name='Tusers',
            field=models.IntegerField(default=1, max_length=4294967295),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='third',
            name='Iusers',
            field=models.IntegerField(default=1, max_length=4294967295),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='third',
            name='Tusers',
            field=models.IntegerField(default=1, max_length=4294967295),
            preserve_default=False,
        ),
    ]
