# Generated by Django 4.0.4 on 2022-06-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0003_rename_susers_second_fusers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
