# Generated by Django 4.0.4 on 2022-06-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0004_delete_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fusers', models.IntegerField(max_length=4294967295)),
                ('Tusers', models.IntegerField(max_length=4294967295)),
                ('Iusers', models.IntegerField(max_length=4294967295)),
            ],
        ),
    ]
