# Generated by Django 4.0.4 on 2022-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0006_app_delete_first_delete_fourth_delete_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='years',
            field=models.IntegerField(default=2006),
        ),
        migrations.AlterField(
            model_name='app',
            name='users',
            field=models.IntegerField(default=1),
        ),
    ]
