# Generated by Django 4.0.4 on 2022-06-03 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0008_rename_platform_app_country_rename_users_app_vistis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='vistis',
            new_name='visits',
        ),
    ]
