# Generated by Django 4.0.4 on 2022-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0009_rename_vistis_app_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
