# Generated by Django 4.0.4 on 2022-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0010_pie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pie',
            name='category',
            field=models.CharField(default='Catogry', max_length=100),
        ),
    ]
