# Generated by Django 4.0.4 on 2022-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0011_alter_pie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addYers', models.IntegerField(default=2006)),
                ('addApp', models.CharField(max_length=50)),
            ],
        ),
    ]
