# Generated by Django 4.0.4 on 2022-06-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0014_delete_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=220)),
                ('value', models.IntegerField(default=10)),
            ],
        ),
    ]
