# Generated by Django 4.0.4 on 2022-06-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0015_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=15)),
            ],
        ),
    ]
